/**
 * Curated cosmetic ingredient dataset — informational only, not medical
 * advice. Ratings are editorial synthesis of widely published cosmetic-
 * chemistry knowledge (comedogenicity scales, common irritant/benefit
 * consensus), not a clinical or regulatory source. Loaded once via
 * run-seed.ts; upserted by canonical_name so re-running is safe. Any
 * ingredient the app encounters later that isn't listed here gets
 * auto-inserted as an unrated placeholder and can be enriched over time.
 */

export type SkinTypeTag =
  | 'oily'
  | 'dry'
  | 'combination'
  | 'normal'
  | 'acne-prone'
  | 'sensitive'
  | 'mature'
  | 'all'

export interface SeedIngredient {
  canonical_name: string
  inci_name?: string
  aliases: string[]
  category: string
  comedogenic_rating: number // 0-5
  irritancy_rating: number // 0-5
  benefit_score: number // 0-10
  skin_type_fit: SkinTypeTag[]
  description: string
}

export const INGREDIENTS_SEED: SeedIngredient[] = [
  // ---------------------------------------------------------------------
  // Base / solvent
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Water',
    inci_name: 'Aqua',
    aliases: ['aqua', 'eau', 'purified water', 'deionized water'],
    category: 'solvent',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Universal solvent and base for most formulations.',
  },

  // ---------------------------------------------------------------------
  // Humectants
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Glycerin',
    aliases: ['glycerol', 'glycerine'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'sensitive', 'all'],
    description: 'Classic humectant that draws water into the skin; very well tolerated.',
  },
  {
    canonical_name: 'Hyaluronic Acid',
    aliases: ['hyaluronan'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 9,
    skin_type_fit: ['dry', 'mature', 'all'],
    description: 'High molecular weight humectant that holds many times its weight in water.',
  },
  {
    canonical_name: 'Sodium Hyaluronate',
    aliases: ['hyaluronate'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 9,
    skin_type_fit: ['dry', 'mature', 'all'],
    description: 'Salt form of hyaluronic acid; smaller molecule that penetrates more easily.',
  },
  {
    canonical_name: 'Panthenol',
    aliases: ['pro-vitamin b5', 'provitamin b5', 'dexpanthenol'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'sensitive', 'all'],
    description: 'Soothing humectant that supports the skin barrier.',
  },
  {
    canonical_name: 'Propanediol',
    aliases: ['1,3-propanediol'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['all'],
    description: 'Plant-derived humectant/solvent, a lighter alternative to propylene glycol.',
  },
  {
    canonical_name: 'Betaine',
    aliases: ['trimethylglycine'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Sugar-beet-derived humectant with mild soothing properties.',
  },
  {
    canonical_name: 'Urea',
    aliases: ['carbamide'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 7,
    skin_type_fit: ['dry', 'mature'],
    description: 'Humectant and gentle keratolytic; higher concentrations can sting broken skin.',
  },
  {
    canonical_name: 'Sorbitol',
    aliases: [],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Sugar-alcohol humectant used to improve texture and hydration.',
  },
  {
    canonical_name: 'Sodium PCA',
    aliases: ['pca'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'all'],
    description: 'Natural moisturizing factor component; strong water-binding humectant.',
  },
  {
    canonical_name: 'Honey Extract',
    aliases: ['mel extract'],
    category: 'humectant',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'normal'],
    description: 'Humectant with mild antibacterial properties.',
  },
  {
    canonical_name: 'Aloe Vera Leaf Juice',
    aliases: ['aloe barbadensis leaf juice', 'aloe extract'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'oily', 'all'],
    description: 'Soothing, lightweight humectant with a long history of topical use.',
  },
  {
    canonical_name: 'Polyglutamic Acid',
    aliases: ['pga'],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'mature'],
    description: 'Film-forming humectant that helps reduce transepidermal water loss.',
  },

  // ---------------------------------------------------------------------
  // Emollients
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Squalane',
    aliases: ['squalane oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'combination', 'all'],
    description: 'Lightweight, non-greasy emollient that closely mimics skin lipids.',
  },
  {
    canonical_name: 'Caprylic/Capric Triglyceride',
    aliases: ['ccт', 'fractionated coconut oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'combination', 'all'],
    description: 'Lightweight emollient ester, commonly used to improve spreadability.',
  },
  {
    canonical_name: 'Isopropyl Myristate',
    aliases: [],
    category: 'emollient',
    comedogenic_rating: 4,
    irritancy_rating: 1,
    benefit_score: 4,
    skin_type_fit: ['dry'],
    description: 'Fast-absorbing emollient; higher comedogenic potential, can be an issue for acne-prone skin.',
  },
  {
    canonical_name: 'Cetearyl Alcohol',
    aliases: ['cetostearyl alcohol'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'all'],
    description: 'Fatty (non-drying) alcohol used as an emollient and emulsion stabilizer.',
  },
  {
    canonical_name: 'Shea Butter',
    aliases: ['butyrospermum parkii butter'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'mature'],
    description: 'Rich, nourishing emollient with a favorable comedogenicity profile.',
  },
  {
    canonical_name: 'Jojoba Oil',
    aliases: ['simmondsia chinensis seed oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'combination', 'oily', 'all'],
    description: 'Liquid wax that closely resembles human sebum; well tolerated by most skin types.',
  },
  {
    canonical_name: 'Argan Oil',
    aliases: ['argania spinosa kernel oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'mature'],
    description: 'Antioxidant-rich emollient oil, moderately light texture.',
  },
  {
    canonical_name: 'Coconut Oil',
    aliases: ['cocos nucifera oil'],
    category: 'emollient',
    comedogenic_rating: 4,
    irritancy_rating: 0,
    benefit_score: 4,
    skin_type_fit: ['dry'],
    description: 'Rich emollient with a high comedogenic rating; often unsuitable for acne-prone skin.',
  },
  {
    canonical_name: 'Sunflower Seed Oil',
    aliases: ['helianthus annuus seed oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'all'],
    description: 'Linoleic-acid-rich oil that supports barrier function; low comedogenicity.',
  },
  {
    canonical_name: 'Olive Oil',
    aliases: ['olea europaea fruit oil'],
    category: 'emollient',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry'],
    description: 'Heavy emollient oil, moderate comedogenic potential.',
  },
  {
    canonical_name: 'Grapeseed Oil',
    aliases: ['vitis vinifera seed oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['combination', 'oily'],
    description: 'Light, antioxidant-containing oil that absorbs quickly.',
  },
  {
    canonical_name: 'Rosehip Oil',
    aliases: ['rosa canina fruit oil', 'rosa mosqueta oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'mature', 'combination'],
    description: 'Vitamin-A-precursor-rich oil valued for texture and tone support.',
  },
  {
    canonical_name: 'Marula Oil',
    aliases: ['sclerocarya birrea seed oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'mature', 'all'],
    description: 'Antioxidant-rich, lightweight facial oil.',
  },
  {
    canonical_name: 'Isopropyl Palmitate',
    aliases: [],
    category: 'emollient',
    comedogenic_rating: 4,
    irritancy_rating: 1,
    benefit_score: 4,
    skin_type_fit: ['dry'],
    description: 'Common emollient ester; relatively high comedogenic potential.',
  },
  {
    canonical_name: 'Ethylhexyl Palmitate',
    aliases: ['octyl palmitate'],
    category: 'emollient',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'combination'],
    description: 'Lightweight ester emollient used to improve slip and finish.',
  },

  // ---------------------------------------------------------------------
  // Occlusives
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Petrolatum',
    aliases: ['petroleum jelly', 'paraffinum liquidum'],
    category: 'occlusive',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'sensitive'],
    description: 'Highly effective barrier occlusive; non-comedogenic despite its reputation.',
  },
  {
    canonical_name: 'Dimethicone',
    aliases: ['polydimethylsiloxane'],
    category: 'occlusive',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['all'],
    description: 'Silicone occlusive that smooths texture and reduces water loss; non-comedogenic.',
  },
  {
    canonical_name: 'Mineral Oil',
    aliases: ['paraffinum perliquidum', 'liquid paraffin'],
    category: 'occlusive',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'sensitive'],
    description: 'Purified occlusive oil; non-comedogenic in cosmetic grade despite common myths.',
  },
  {
    canonical_name: 'Beeswax',
    aliases: ['cera alba'],
    category: 'occlusive',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry'],
    description: 'Natural occlusive/thickener with moderate comedogenic potential.',
  },
  {
    canonical_name: 'Lanolin',
    aliases: ['wool wax'],
    category: 'occlusive',
    comedogenic_rating: 2,
    irritancy_rating: 2,
    benefit_score: 5,
    skin_type_fit: ['dry'],
    description: 'Effective occlusive derived from sheep wool; can be sensitizing for some.',
  },
  {
    canonical_name: 'Candelilla Wax',
    aliases: ['euphorbia cerifera wax'],
    category: 'occlusive',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 4,
    skin_type_fit: ['dry'],
    description: 'Plant-derived wax used as a texture/occlusive agent.',
  },

  // ---------------------------------------------------------------------
  // Exfoliant acids
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Glycolic Acid',
    aliases: ['aha'],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 8,
    skin_type_fit: ['mature', 'oily'],
    description: 'Small-molecule AHA exfoliant that resurfaces texture and evens tone.',
  },
  {
    canonical_name: 'Lactic Acid',
    aliases: [],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 8,
    skin_type_fit: ['mature', 'dry', 'sensitive'],
    description: 'Gentler AHA that also has humectant properties; good for drier or sensitive skin.',
  },
  {
    canonical_name: 'Salicylic Acid',
    aliases: ['bha'],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 8,
    skin_type_fit: ['oily', 'acne-prone', 'combination'],
    description: 'Oil-soluble BHA that penetrates pores; well suited to oily/acne-prone skin.',
  },
  {
    canonical_name: 'Mandelic Acid',
    aliases: [],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'acne-prone'],
    description: 'Larger-molecule AHA that penetrates more slowly; gentler on sensitive/acne-prone skin.',
  },
  {
    canonical_name: 'Malic Acid',
    aliases: [],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 6,
    skin_type_fit: ['mature'],
    description: 'AHA often used alongside other acids to boost exfoliation and pH efficacy.',
  },
  {
    canonical_name: 'Tartaric Acid',
    aliases: [],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 5,
    skin_type_fit: ['mature'],
    description: 'AHA used in acid blends for exfoliation and pH adjustment.',
  },
  {
    canonical_name: 'Citric Acid',
    aliases: [],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Mild AHA and common pH adjuster in cosmetic formulas.',
  },
  {
    canonical_name: 'Gluconolactone',
    aliases: ['pha'],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'dry', 'mature'],
    description: 'Polyhydroxy acid (PHA): gentler exfoliant with humectant properties, good for sensitive skin.',
  },
  {
    canonical_name: 'Lactobionic Acid',
    aliases: ['pha'],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'mature'],
    description: 'PHA exfoliant with antioxidant properties; gentle option for reactive skin.',
  },
  {
    canonical_name: 'Papain',
    aliases: ['papaya enzyme'],
    category: 'exfoliant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 5,
    skin_type_fit: ['sensitive'],
    description: 'Enzymatic exfoliant derived from papaya; gentler mechanism than acids.',
  },

  // ---------------------------------------------------------------------
  // Actives: vitamins / antioxidants
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Niacinamide',
    aliases: ['vitamin b3', 'nicotinamide'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 9,
    skin_type_fit: ['oily', 'acne-prone', 'combination', 'all'],
    description: 'Versatile active that supports barrier function, tone, and oil regulation.',
  },
  {
    canonical_name: 'Retinol',
    aliases: ['vitamin a', 'retinyl'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 4,
    benefit_score: 9,
    skin_type_fit: ['mature', 'oily'],
    description: 'Gold-standard anti-aging active; can be irritating, especially when starting out.',
  },
  {
    canonical_name: 'Retinaldehyde',
    aliases: ['retinal'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 8,
    skin_type_fit: ['mature', 'oily'],
    description: 'Retinoid closer to active retinoic acid than retinol; effective with moderate irritation.',
  },
  {
    canonical_name: 'Bakuchiol',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'mature'],
    description: 'Plant-derived retinol alternative with a gentler tolerability profile.',
  },
  {
    canonical_name: 'Ascorbic Acid',
    aliases: ['vitamin c', 'l-ascorbic acid'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 8,
    skin_type_fit: ['mature', 'normal'],
    description: 'Potent antioxidant and brightening active; the most effective but least stable vitamin C form.',
  },
  {
    canonical_name: 'Sodium Ascorbyl Phosphate',
    aliases: ['sap', 'vitamin c ester'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'acne-prone'],
    description: 'Stable, gentler vitamin C derivative, well suited to sensitive/acne-prone skin.',
  },
  {
    canonical_name: 'Magnesium Ascorbyl Phosphate',
    aliases: ['map'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive'],
    description: 'Stable vitamin C derivative with mild brightening/antioxidant benefit.',
  },
  {
    canonical_name: 'Ascorbyl Glucoside',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive'],
    description: 'Stable vitamin C derivative, converts to active ascorbic acid in skin.',
  },
  {
    canonical_name: 'Tocopherol',
    aliases: ['vitamin e'],
    category: 'active',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['dry', 'mature', 'all'],
    description: 'Antioxidant vitamin, often paired with vitamin C to boost stability.',
  },
  {
    canonical_name: 'Ferulic Acid',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['mature', 'all'],
    description: 'Antioxidant that stabilizes and boosts the efficacy of vitamins C and E.',
  },
  {
    canonical_name: 'Alpha Arbutin',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['mature', 'normal'],
    description: 'Tyrosinase-inhibiting brightening active, gentler than hydroquinone.',
  },
  {
    canonical_name: 'Azelaic Acid',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 8,
    skin_type_fit: ['acne-prone', 'sensitive', 'oily'],
    description: 'Multi-purpose active for redness, tone, and mild acne; generally well tolerated.',
  },
  {
    canonical_name: 'Kojic Acid',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 6,
    skin_type_fit: ['mature'],
    description: 'Brightening active; can be sensitizing at higher concentrations.',
  },
  {
    canonical_name: 'Tranexamic Acid',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['mature', 'sensitive'],
    description: 'Brightening active that targets pigmentation with low irritation.',
  },
  {
    canonical_name: 'Resveratrol',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['mature', 'all'],
    description: 'Polyphenol antioxidant with mild anti-aging benefits.',
  },
  {
    canonical_name: 'Green Tea Extract',
    aliases: ['camellia sinensis leaf extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['oily', 'sensitive', 'all'],
    description: 'Antioxidant plant extract with mild soothing and oil-control properties.',
  },
  {
    canonical_name: 'Centella Asiatica Extract',
    aliases: ['cica', 'gotu kola extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'acne-prone', 'all'],
    description: 'Soothing, barrier-supportive extract popular for reactive/compromised skin.',
  },
  {
    canonical_name: 'Panax Ginseng Root Extract',
    aliases: ['ginseng extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['mature'],
    description: 'Antioxidant botanical extract with mild anti-aging associations.',
  },

  // ---------------------------------------------------------------------
  // Peptides
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Palmitoyl Pentapeptide-4',
    aliases: ['matrixyl'],
    category: 'peptide',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['mature'],
    description: 'Signal peptide marketed to support collagen production.',
  },
  {
    canonical_name: 'Copper Tripeptide-1',
    aliases: ['copper peptides', 'ghk-cu'],
    category: 'peptide',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['mature'],
    description: 'Peptide-mineral complex associated with wound healing and firmness support.',
  },
  {
    canonical_name: 'Acetyl Hexapeptide-8',
    aliases: ['argireline'],
    category: 'peptide',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['mature'],
    description: 'Peptide marketed for a topical, temporary muscle-relaxing effect on fine lines.',
  },
  {
    canonical_name: 'Palmitoyl Tripeptide-1',
    aliases: [],
    category: 'peptide',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['mature'],
    description: 'Signal peptide often combined with other peptides for firmness claims.',
  },

  // ---------------------------------------------------------------------
  // Preservatives
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Phenoxyethanol',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Broad-spectrum preservative, one of the most widely used and best tolerated.',
  },
  {
    canonical_name: 'Sodium Benzoate',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Common preservative, effective at low pH.',
  },
  {
    canonical_name: 'Potassium Sorbate',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Mild preservative typically paired with sodium benzoate.',
  },
  {
    canonical_name: 'Benzyl Alcohol',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 3,
    skin_type_fit: [],
    description: 'Preservative/solvent; can be sensitizing for reactive skin at higher levels.',
  },
  {
    canonical_name: 'Ethylhexylglycerin',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Preservative booster and mild skin conditioner.',
  },
  {
    canonical_name: 'Methylparaben',
    aliases: ['paraben'],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Widely studied preservative; generally well tolerated but a common consumer concern.',
  },
  {
    canonical_name: 'Propylparaben',
    aliases: ['paraben'],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Preservative from the paraben family, often used alongside methylparaben.',
  },
  {
    canonical_name: 'Chlorphenesin',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Preservative with mild antimicrobial activity.',
  },
  {
    canonical_name: 'Sodium Dehydroacetate',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Preservative used across a range of pH conditions.',
  },
  {
    canonical_name: 'Caprylyl Glycol',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 3,
    skin_type_fit: ['all'],
    description: 'Preservative booster and mild humectant.',
  },
  {
    canonical_name: 'Disodium EDTA',
    aliases: ['edta'],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Chelating agent that improves preservative efficacy and product stability.',
  },
  {
    canonical_name: 'Benzoic Acid',
    aliases: [],
    category: 'preservative',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Preservative and pH adjuster, effective at acidic pH.',
  },

  // ---------------------------------------------------------------------
  // Fragrance / essential oils
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Fragrance',
    inci_name: 'Parfum',
    aliases: ['parfum', 'perfume'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Undisclosed fragrance blend; a common trigger for sensitive skin.',
  },
  {
    canonical_name: 'Linalool',
    aliases: [],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Common fragrance allergen, naturally occurring in many essential oils.',
  },
  {
    canonical_name: 'Limonene',
    aliases: [],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Citrus-derived fragrance component and known contact allergen.',
  },
  {
    canonical_name: 'Citronellol',
    aliases: [],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Fragrance component associated with contact sensitization in some users.',
  },
  {
    canonical_name: 'Geraniol',
    aliases: [],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Common fragrance allergen found in rose- and geranium-scented products.',
  },
  {
    canonical_name: 'Eugenol',
    aliases: [],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Clove-derived fragrance component, a recognized sensitizer.',
  },
  {
    canonical_name: 'Lavender Oil',
    aliases: ['lavandula angustifolia oil'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Essential oil with a pleasant scent but real sensitization potential.',
  },
  {
    canonical_name: 'Tea Tree Oil',
    aliases: ['melaleuca alternifolia oil'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 4,
    skin_type_fit: ['oily'],
    description: 'Antimicrobial essential oil with acne-related benefits, but irritating undiluted.',
  },
  {
    canonical_name: 'Peppermint Oil',
    aliases: ['mentha piperita oil'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Cooling essential oil that frequently irritates sensitive or compromised skin.',
  },
  {
    canonical_name: 'Citrus Extract',
    aliases: ['citrus limon peel extract'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Botanical extract used for scent; can be irritating, especially with sun exposure.',
  },
  {
    canonical_name: 'Ylang Ylang Oil',
    aliases: ['cananga odorata flower oil'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Floral essential oil, common fragrance allergen source.',
  },
  {
    canonical_name: 'Rose Oil',
    aliases: ['rosa damascena flower oil'],
    category: 'fragrance',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 2,
    skin_type_fit: [],
    description: 'Floral essential oil valued for scent; can sensitize reactive skin.',
  },

  // ---------------------------------------------------------------------
  // Alcohols
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Alcohol Denat.',
    aliases: ['denatured alcohol', 'sd alcohol'],
    category: 'alcohol',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 2,
    skin_type_fit: ['oily'],
    description: 'Fast-drying solvent alcohol; can be drying/irritating for dry or sensitive skin.',
  },
  {
    canonical_name: 'Cetyl Alcohol',
    aliases: [],
    category: 'alcohol',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'all'],
    description: 'Fatty alcohol emollient/thickener; not drying despite the name.',
  },
  {
    canonical_name: 'Stearyl Alcohol',
    aliases: [],
    category: 'alcohol',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'all'],
    description: 'Fatty alcohol used as an emollient and thickener; non-drying.',
  },
  {
    canonical_name: 'Isopropyl Alcohol',
    aliases: [],
    category: 'alcohol',
    comedogenic_rating: 0,
    irritancy_rating: 4,
    benefit_score: 1,
    skin_type_fit: [],
    description: 'Strong drying solvent alcohol; can compromise the skin barrier with frequent use.',
  },
  {
    canonical_name: 'Behenyl Alcohol',
    aliases: [],
    category: 'alcohol',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 4,
    skin_type_fit: ['dry'],
    description: 'Fatty alcohol emollient/thickener, non-drying.',
  },

  // ---------------------------------------------------------------------
  // Silicones
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Cyclopentasiloxane',
    aliases: [],
    category: 'silicone',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Volatile silicone that gives a silky finish and evaporates cleanly.',
  },
  {
    canonical_name: 'Dimethiconol',
    aliases: [],
    category: 'silicone',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'all'],
    description: 'Silicone conditioning agent that adds slip and shine.',
  },
  {
    canonical_name: 'Cyclohexasiloxane',
    aliases: [],
    category: 'silicone',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Volatile silicone used for a lightweight, smooth finish.',
  },
  {
    canonical_name: 'Phenyl Trimethicone',
    aliases: [],
    category: 'silicone',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Silicone that adds shine and a smooth after-feel.',
  },
  {
    canonical_name: 'Dimethicone Crosspolymer',
    aliases: [],
    category: 'silicone',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['all'],
    description: 'Gel-forming silicone that softens the appearance of pores and lines.',
  },

  // ---------------------------------------------------------------------
  // Sunscreen filters
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Zinc Oxide',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 9,
    skin_type_fit: ['sensitive', 'acne-prone', 'all'],
    description: 'Broad-spectrum mineral UV filter, well tolerated by sensitive/reactive skin.',
  },
  {
    canonical_name: 'Titanium Dioxide',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Mineral UV filter, mainly UVB with some UVA protection.',
  },
  {
    canonical_name: 'Avobenzone',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['normal'],
    description: 'Chemical UVA filter, often paired with stabilizers due to photoinstability.',
  },
  {
    canonical_name: 'Octinoxate',
    aliases: ['ethylhexyl methoxycinnamate'],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['normal'],
    description: 'Chemical UVB filter, widely used but with some environmental concerns.',
  },
  {
    canonical_name: 'Octocrylene',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 1,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['normal'],
    description: 'Chemical UVB filter that also stabilizes avobenzone.',
  },
  {
    canonical_name: 'Homosalate',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 5,
    skin_type_fit: ['normal'],
    description: 'Chemical UVB filter commonly used in sunscreen blends.',
  },
  {
    canonical_name: 'Bemotrizinol',
    aliases: ['tinosorb s'],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['sensitive', 'normal'],
    description: 'Broad-spectrum, photostable chemical UV filter with a strong tolerability profile.',
  },
  {
    canonical_name: 'Bisoctrizole',
    aliases: ['tinosorb m'],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['sensitive', 'normal'],
    description: 'Broad-spectrum organic/mineral hybrid UV filter, well tolerated.',
  },
  {
    canonical_name: 'Ensulizole',
    aliases: [],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 5,
    skin_type_fit: ['normal'],
    description: 'Water-soluble chemical UVB filter.',
  },
  {
    canonical_name: 'Diethylamino Hydroxybenzoyl Hexyl Benzoate',
    aliases: ['uvinul a plus'],
    category: 'sunscreen-filter',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'normal'],
    description: 'Photostable UVA filter used to round out broad-spectrum protection.',
  },

  // ---------------------------------------------------------------------
  // Surfactants
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Sodium Laureth Sulfate',
    aliases: ['sles'],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 3,
    benefit_score: 4,
    skin_type_fit: ['oily'],
    description: 'Strong foaming cleanser; can be drying/irritating with frequent use.',
  },
  {
    canonical_name: 'Sodium Lauryl Sulfate',
    aliases: ['sls'],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 4,
    benefit_score: 3,
    skin_type_fit: [],
    description: 'Strong foaming cleanser with a higher irritation potential than SLES.',
  },
  {
    canonical_name: 'Cocamidopropyl Betaine',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Mild, coconut-derived co-surfactant commonly used to soften harsher cleansers.',
  },
  {
    canonical_name: 'Decyl Glucoside',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'dry', 'all'],
    description: 'Gentle sugar-derived surfactant, well tolerated by sensitive skin.',
  },
  {
    canonical_name: 'Sodium Cocoyl Isethionate',
    aliases: ['sci'],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'dry', 'all'],
    description: 'Mild coconut-derived surfactant popular in "gentle" cleansing bars/washes.',
  },
  {
    canonical_name: 'Lauryl Glucoside',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Mild sugar-derived surfactant used to boost foam without harsh sulfates.',
  },
  {
    canonical_name: 'Coco-Glucoside',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Gentle non-ionic surfactant derived from coconut and fruit sugars.',
  },
  {
    canonical_name: 'Disodium Cocoamphodiacetate',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 6,
    skin_type_fit: ['sensitive'],
    description: 'Mild amphoteric surfactant used to reduce irritation in cleansers.',
  },
  {
    canonical_name: 'Sodium Cocoyl Glutamate',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 7,
    skin_type_fit: ['sensitive', 'dry', 'all'],
    description: 'Amino-acid-derived surfactant, gentle and mildly moisturizing.',
  },
  {
    canonical_name: 'Potassium Cocoate',
    aliases: [],
    category: 'surfactant',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 5,
    skin_type_fit: ['oily'],
    description: 'Saponified-oil-based surfactant used in traditional cleansing bars.',
  },

  // ---------------------------------------------------------------------
  // Thickeners / film formers
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Xanthan Gum',
    aliases: [],
    category: 'thickener',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Natural polysaccharide thickener with no known skin activity.',
  },
  {
    canonical_name: 'Carbomer',
    aliases: [],
    category: 'thickener',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Synthetic gelling agent used to build gel and lotion textures.',
  },
  {
    canonical_name: 'Sodium Polyacrylate',
    aliases: [],
    category: 'thickener',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Thickening polymer used to adjust product viscosity.',
  },
  {
    canonical_name: 'Hydroxyethylcellulose',
    aliases: [],
    category: 'thickener',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Cellulose-derived thickener with no known skin activity.',
  },
  {
    canonical_name: 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
    aliases: [],
    category: 'thickener',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Thickening/stabilizing polymer used in gels and emulsions.',
  },
  {
    canonical_name: 'PVP',
    aliases: ['polyvinylpyrrolidone'],
    category: 'film-former',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 2,
    skin_type_fit: ['all'],
    description: 'Film-forming polymer used to improve product hold and texture.',
  },

  // ---------------------------------------------------------------------
  // Colorants / misc
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Mica',
    aliases: [],
    category: 'colorant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 1,
    skin_type_fit: ['all'],
    description: 'Mineral pigment used for shimmer/color; inert on skin.',
  },
  {
    canonical_name: 'Titanium Dioxide (colorant use)',
    inci_name: 'CI 77891',
    aliases: ['ci 77891'],
    category: 'colorant',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 1,
    skin_type_fit: ['all'],
    description: 'White pigment used for opacity/color in makeup-adjacent formulas.',
  },
  {
    canonical_name: 'Iron Oxides',
    inci_name: 'CI 77491, CI 77492, CI 77499',
    aliases: ['ci 77491', 'ci 77492', 'ci 77499'],
    category: 'colorant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 1,
    skin_type_fit: ['all'],
    description: 'Mineral pigments used for tinting; also help block visible/blue light.',
  },
  {
    canonical_name: 'Red 40',
    inci_name: 'CI 16035',
    aliases: ['ci 16035'],
    category: 'colorant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 0,
    skin_type_fit: [],
    description: 'Synthetic dye used for color; occasional sensitizer.',
  },
  {
    canonical_name: 'Blue 1',
    inci_name: 'CI 42090',
    aliases: ['ci 42090'],
    category: 'colorant',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 0,
    skin_type_fit: [],
    description: 'Synthetic dye used for color in cosmetic formulas.',
  },

  // ---------------------------------------------------------------------
  // Additional actives / botanicals rounding out common formulas
  // ---------------------------------------------------------------------
  {
    canonical_name: 'Allantoin',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'dry', 'all'],
    description: 'Soothing, skin-conditioning agent, often used to calm reactive formulas.',
  },
  {
    canonical_name: 'Bisabolol',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'all'],
    description: 'Chamomile-derived soothing agent used to calm irritation.',
  },
  {
    canonical_name: 'Chamomile Extract',
    aliases: ['matricaria chamomilla extract', 'anthemis nobilis extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 5,
    skin_type_fit: ['sensitive'],
    description: 'Soothing botanical extract; rare sensitizer for ragweed-allergic individuals.',
  },
  {
    canonical_name: 'Licorice Root Extract',
    aliases: ['glycyrrhiza glabra root extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'mature'],
    description: 'Soothing, mildly brightening botanical extract.',
  },
  {
    canonical_name: 'Witch Hazel',
    aliases: ['hamamelis virginiana extract'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 4,
    skin_type_fit: ['oily'],
    description: 'Astringent botanical extract; formulations with alcohol can be drying.',
  },
  {
    canonical_name: 'Zinc PCA',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['oily', 'acne-prone'],
    description: 'Zinc salt used for mild oil-control and soothing benefits.',
  },
  {
    canonical_name: 'Caffeine',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['oily', 'normal'],
    description: 'Antioxidant with mild de-puffing and vasoconstrictive properties.',
  },
  {
    canonical_name: 'Niacin',
    aliases: ['nicotinic acid'],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 2,
    benefit_score: 4,
    skin_type_fit: [],
    description: 'Vitamin B3 precursor; can cause temporary flushing, unlike niacinamide.',
  },
  {
    canonical_name: 'Adenosine',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['mature'],
    description: 'Anti-wrinkle active recognized in several regulatory markets.',
  },
  {
    canonical_name: 'Beta-Glucan',
    aliases: [],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['sensitive', 'dry', 'all'],
    description: 'Soothing polysaccharide that supports hydration and barrier repair.',
  },
  {
    canonical_name: 'Ceramide NP',
    aliases: ['ceramide 3'],
    category: 'emollient',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'sensitive', 'mature', 'all'],
    description: 'Barrier lipid that replenishes the skin’s natural ceramide content.',
  },
  {
    canonical_name: 'Cholesterol',
    aliases: [],
    category: 'emollient',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'mature'],
    description: 'Barrier lipid, often combined with ceramides and fatty acids.',
  },
  {
    canonical_name: 'Linoleic Acid',
    aliases: [],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['acne-prone', 'oily'],
    description: 'Essential fatty acid associated with a lower comedogenic profile than oleic acid.',
  },
  {
    canonical_name: 'Squalene',
    aliases: [],
    category: 'emollient',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry'],
    description: 'Unsaturated precursor to squalane; less stable and slightly more comedogenic.',
  },
  {
    canonical_name: 'Niacinamide/Zinc PCA Complex',
    aliases: [],
    category: 'active',
    comedogenic_rating: 0,
    irritancy_rating: 1,
    benefit_score: 8,
    skin_type_fit: ['oily', 'acne-prone'],
    description: 'Combination active formulated for oil regulation and pore appearance.',
  },
  {
    canonical_name: 'Panthenyl Triacetate',
    aliases: [],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 5,
    skin_type_fit: ['dry', 'all'],
    description: 'Oil-soluble form of panthenol, used in emollient-rich formulas.',
  },
  {
    canonical_name: 'Sea Buckthorn Oil',
    aliases: ['hippophae rhamnoides oil'],
    category: 'emollient',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'mature'],
    description: 'Carotenoid-rich oil valued for antioxidant and barrier-support properties.',
  },
  {
    canonical_name: 'Evening Primrose Oil',
    aliases: ['oenothera biennis oil'],
    category: 'emollient',
    comedogenic_rating: 2,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'sensitive'],
    description: 'GLA-rich oil associated with barrier support and mild anti-inflammatory benefit.',
  },
  {
    canonical_name: 'Meadowfoam Seed Oil',
    aliases: ['limnanthes alba seed oil'],
    category: 'emollient',
    comedogenic_rating: 1,
    irritancy_rating: 0,
    benefit_score: 6,
    skin_type_fit: ['dry', 'combination', 'all'],
    description: 'Highly stable, lightweight emollient oil.',
  },
  {
    canonical_name: 'Sodium Hyaluronate Crosspolymer',
    aliases: [],
    category: 'humectant',
    comedogenic_rating: 0,
    irritancy_rating: 0,
    benefit_score: 8,
    skin_type_fit: ['dry', 'mature', 'all'],
    description: 'Cross-linked hyaluronic acid that forms a hydrating film on the skin surface.',
  },
]
