-- Curated ingredient seed data, generated from supabase/seed/ingredients-seed.ts.
-- Run this in the Supabase SQL Editor AFTER applying supabase/schema.sql.
-- Safe to re-run: upserts by canonical_name.
-- (No terminal/service-role key needed — this is a plain SQL alternative to
-- `npm run seed` for setups where running a local Node script isn't an option.)

insert into ingredients
  (canonical_name, inci_name, aliases, category, comedogenic_rating, irritancy_rating, benefit_score, skin_type_fit, description, is_rated, source)
values
  ('Water', 'Aqua', ARRAY['aqua', 'eau', 'purified water', 'deionized water']::text[], 'solvent', 0, 0, 3, ARRAY['all']::text[], 'Universal solvent and base for most formulations.', true, 'seed'),
  ('Glycerin', NULL, ARRAY['glycerol', 'glycerine']::text[], 'humectant', 0, 0, 8, ARRAY['dry', 'sensitive', 'all']::text[], 'Classic humectant that draws water into the skin; very well tolerated.', true, 'seed'),
  ('Hyaluronic Acid', NULL, ARRAY['hyaluronan']::text[], 'humectant', 0, 0, 9, ARRAY['dry', 'mature', 'all']::text[], 'High molecular weight humectant that holds many times its weight in water.', true, 'seed'),
  ('Sodium Hyaluronate', NULL, ARRAY['hyaluronate']::text[], 'humectant', 0, 0, 9, ARRAY['dry', 'mature', 'all']::text[], 'Salt form of hyaluronic acid; smaller molecule that penetrates more easily.', true, 'seed'),
  ('Panthenol', NULL, ARRAY['pro-vitamin b5', 'provitamin b5', 'dexpanthenol']::text[], 'humectant', 0, 0, 8, ARRAY['dry', 'sensitive', 'all']::text[], 'Soothing humectant that supports the skin barrier.', true, 'seed'),
  ('Propanediol', NULL, ARRAY['1,3-propanediol']::text[], 'humectant', 0, 0, 6, ARRAY['all']::text[], 'Plant-derived humectant/solvent, a lighter alternative to propylene glycol.', true, 'seed'),
  ('Betaine', NULL, ARRAY['trimethylglycine']::text[], 'humectant', 0, 0, 6, ARRAY['sensitive', 'all']::text[], 'Sugar-beet-derived humectant with mild soothing properties.', true, 'seed'),
  ('Urea', NULL, ARRAY['carbamide']::text[], 'humectant', 0, 2, 7, ARRAY['dry', 'mature']::text[], 'Humectant and gentle keratolytic; higher concentrations can sting broken skin.', true, 'seed'),
  ('Sorbitol', NULL, ARRAY[]::text[], 'humectant', 0, 0, 5, ARRAY['all']::text[], 'Sugar-alcohol humectant used to improve texture and hydration.', true, 'seed'),
  ('Sodium PCA', NULL, ARRAY['pca']::text[], 'humectant', 0, 0, 7, ARRAY['dry', 'all']::text[], 'Natural moisturizing factor component; strong water-binding humectant.', true, 'seed'),
  ('Honey Extract', NULL, ARRAY['mel extract']::text[], 'humectant', 1, 0, 6, ARRAY['dry', 'normal']::text[], 'Humectant with mild antibacterial properties.', true, 'seed'),
  ('Aloe Vera Leaf Juice', NULL, ARRAY['aloe barbadensis leaf juice', 'aloe extract']::text[], 'humectant', 0, 0, 7, ARRAY['sensitive', 'oily', 'all']::text[], 'Soothing, lightweight humectant with a long history of topical use.', true, 'seed'),
  ('Polyglutamic Acid', NULL, ARRAY['pga']::text[], 'humectant', 0, 0, 7, ARRAY['dry', 'mature']::text[], 'Film-forming humectant that helps reduce transepidermal water loss.', true, 'seed'),
  ('Squalane', NULL, ARRAY['squalane oil']::text[], 'emollient', 1, 0, 8, ARRAY['dry', 'combination', 'all']::text[], 'Lightweight, non-greasy emollient that closely mimics skin lipids.', true, 'seed'),
  ('Caprylic/Capric Triglyceride', NULL, ARRAY['ccт', 'fractionated coconut oil']::text[], 'emollient', 1, 0, 6, ARRAY['dry', 'combination', 'all']::text[], 'Lightweight emollient ester, commonly used to improve spreadability.', true, 'seed'),
  ('Isopropyl Myristate', NULL, ARRAY[]::text[], 'emollient', 4, 1, 4, ARRAY['dry']::text[], 'Fast-absorbing emollient; higher comedogenic potential, can be an issue for acne-prone skin.', true, 'seed'),
  ('Cetearyl Alcohol', NULL, ARRAY['cetostearyl alcohol']::text[], 'emollient', 1, 0, 5, ARRAY['dry', 'all']::text[], 'Fatty (non-drying) alcohol used as an emollient and emulsion stabilizer.', true, 'seed'),
  ('Shea Butter', NULL, ARRAY['butyrospermum parkii butter']::text[], 'emollient', 1, 0, 8, ARRAY['dry', 'mature']::text[], 'Rich, nourishing emollient with a favorable comedogenicity profile.', true, 'seed'),
  ('Jojoba Oil', NULL, ARRAY['simmondsia chinensis seed oil']::text[], 'emollient', 1, 0, 8, ARRAY['dry', 'combination', 'oily', 'all']::text[], 'Liquid wax that closely resembles human sebum; well tolerated by most skin types.', true, 'seed'),
  ('Argan Oil', NULL, ARRAY['argania spinosa kernel oil']::text[], 'emollient', 1, 0, 8, ARRAY['dry', 'mature']::text[], 'Antioxidant-rich emollient oil, moderately light texture.', true, 'seed'),
  ('Coconut Oil', NULL, ARRAY['cocos nucifera oil']::text[], 'emollient', 4, 0, 4, ARRAY['dry']::text[], 'Rich emollient with a high comedogenic rating; often unsuitable for acne-prone skin.', true, 'seed'),
  ('Sunflower Seed Oil', NULL, ARRAY['helianthus annuus seed oil']::text[], 'emollient', 1, 0, 7, ARRAY['dry', 'all']::text[], 'Linoleic-acid-rich oil that supports barrier function; low comedogenicity.', true, 'seed'),
  ('Olive Oil', NULL, ARRAY['olea europaea fruit oil']::text[], 'emollient', 2, 0, 5, ARRAY['dry']::text[], 'Heavy emollient oil, moderate comedogenic potential.', true, 'seed'),
  ('Grapeseed Oil', NULL, ARRAY['vitis vinifera seed oil']::text[], 'emollient', 1, 0, 6, ARRAY['combination', 'oily']::text[], 'Light, antioxidant-containing oil that absorbs quickly.', true, 'seed'),
  ('Rosehip Oil', NULL, ARRAY['rosa canina fruit oil', 'rosa mosqueta oil']::text[], 'emollient', 1, 0, 8, ARRAY['dry', 'mature', 'combination']::text[], 'Vitamin-A-precursor-rich oil valued for texture and tone support.', true, 'seed'),
  ('Marula Oil', NULL, ARRAY['sclerocarya birrea seed oil']::text[], 'emollient', 1, 0, 7, ARRAY['dry', 'mature', 'all']::text[], 'Antioxidant-rich, lightweight facial oil.', true, 'seed'),
  ('Isopropyl Palmitate', NULL, ARRAY[]::text[], 'emollient', 4, 1, 4, ARRAY['dry']::text[], 'Common emollient ester; relatively high comedogenic potential.', true, 'seed'),
  ('Ethylhexyl Palmitate', NULL, ARRAY['octyl palmitate']::text[], 'emollient', 2, 0, 5, ARRAY['dry', 'combination']::text[], 'Lightweight ester emollient used to improve slip and finish.', true, 'seed'),
  ('Petrolatum', NULL, ARRAY['petroleum jelly', 'paraffinum liquidum']::text[], 'occlusive', 0, 0, 7, ARRAY['dry', 'sensitive']::text[], 'Highly effective barrier occlusive; non-comedogenic despite its reputation.', true, 'seed'),
  ('Dimethicone', NULL, ARRAY['polydimethylsiloxane']::text[], 'occlusive', 0, 0, 6, ARRAY['all']::text[], 'Silicone occlusive that smooths texture and reduces water loss; non-comedogenic.', true, 'seed'),
  ('Mineral Oil', NULL, ARRAY['paraffinum perliquidum', 'liquid paraffin']::text[], 'occlusive', 1, 0, 5, ARRAY['dry', 'sensitive']::text[], 'Purified occlusive oil; non-comedogenic in cosmetic grade despite common myths.', true, 'seed'),
  ('Beeswax', NULL, ARRAY['cera alba']::text[], 'occlusive', 2, 0, 5, ARRAY['dry']::text[], 'Natural occlusive/thickener with moderate comedogenic potential.', true, 'seed'),
  ('Lanolin', NULL, ARRAY['wool wax']::text[], 'occlusive', 2, 2, 5, ARRAY['dry']::text[], 'Effective occlusive derived from sheep wool; can be sensitizing for some.', true, 'seed'),
  ('Candelilla Wax', NULL, ARRAY['euphorbia cerifera wax']::text[], 'occlusive', 1, 0, 4, ARRAY['dry']::text[], 'Plant-derived wax used as a texture/occlusive agent.', true, 'seed'),
  ('Glycolic Acid', NULL, ARRAY['aha']::text[], 'exfoliant', 0, 3, 8, ARRAY['mature', 'oily']::text[], 'Small-molecule AHA exfoliant that resurfaces texture and evens tone.', true, 'seed'),
  ('Lactic Acid', NULL, ARRAY[]::text[], 'exfoliant', 0, 2, 8, ARRAY['mature', 'dry', 'sensitive']::text[], 'Gentler AHA that also has humectant properties; good for drier or sensitive skin.', true, 'seed'),
  ('Salicylic Acid', NULL, ARRAY['bha']::text[], 'exfoliant', 0, 2, 8, ARRAY['oily', 'acne-prone', 'combination']::text[], 'Oil-soluble BHA that penetrates pores; well suited to oily/acne-prone skin.', true, 'seed'),
  ('Mandelic Acid', NULL, ARRAY[]::text[], 'exfoliant', 0, 1, 7, ARRAY['sensitive', 'acne-prone']::text[], 'Larger-molecule AHA that penetrates more slowly; gentler on sensitive/acne-prone skin.', true, 'seed'),
  ('Malic Acid', NULL, ARRAY[]::text[], 'exfoliant', 0, 2, 6, ARRAY['mature']::text[], 'AHA often used alongside other acids to boost exfoliation and pH efficacy.', true, 'seed'),
  ('Tartaric Acid', NULL, ARRAY[]::text[], 'exfoliant', 0, 2, 5, ARRAY['mature']::text[], 'AHA used in acid blends for exfoliation and pH adjustment.', true, 'seed'),
  ('Citric Acid', NULL, ARRAY[]::text[], 'exfoliant', 0, 2, 5, ARRAY['all']::text[], 'Mild AHA and common pH adjuster in cosmetic formulas.', true, 'seed'),
  ('Gluconolactone', NULL, ARRAY['pha']::text[], 'exfoliant', 0, 1, 7, ARRAY['sensitive', 'dry', 'mature']::text[], 'Polyhydroxy acid (PHA): gentler exfoliant with humectant properties, good for sensitive skin.', true, 'seed'),
  ('Lactobionic Acid', NULL, ARRAY['pha']::text[], 'exfoliant', 0, 1, 7, ARRAY['sensitive', 'mature']::text[], 'PHA exfoliant with antioxidant properties; gentle option for reactive skin.', true, 'seed'),
  ('Papain', NULL, ARRAY['papaya enzyme']::text[], 'exfoliant', 0, 2, 5, ARRAY['sensitive']::text[], 'Enzymatic exfoliant derived from papaya; gentler mechanism than acids.', true, 'seed'),
  ('Niacinamide', NULL, ARRAY['vitamin b3', 'nicotinamide']::text[], 'active', 0, 1, 9, ARRAY['oily', 'acne-prone', 'combination', 'all']::text[], 'Versatile active that supports barrier function, tone, and oil regulation.', true, 'seed'),
  ('Retinol', NULL, ARRAY['vitamin a', 'retinyl']::text[], 'active', 0, 4, 9, ARRAY['mature', 'oily']::text[], 'Gold-standard anti-aging active; can be irritating, especially when starting out.', true, 'seed'),
  ('Retinaldehyde', NULL, ARRAY['retinal']::text[], 'active', 0, 3, 8, ARRAY['mature', 'oily']::text[], 'Retinoid closer to active retinoic acid than retinol; effective with moderate irritation.', true, 'seed'),
  ('Bakuchiol', NULL, ARRAY[]::text[], 'active', 0, 1, 7, ARRAY['sensitive', 'mature']::text[], 'Plant-derived retinol alternative with a gentler tolerability profile.', true, 'seed'),
  ('Ascorbic Acid', NULL, ARRAY['vitamin c', 'l-ascorbic acid']::text[], 'active', 0, 3, 8, ARRAY['mature', 'normal']::text[], 'Potent antioxidant and brightening active; the most effective but least stable vitamin C form.', true, 'seed'),
  ('Sodium Ascorbyl Phosphate', NULL, ARRAY['sap', 'vitamin c ester']::text[], 'active', 0, 1, 6, ARRAY['sensitive', 'acne-prone']::text[], 'Stable, gentler vitamin C derivative, well suited to sensitive/acne-prone skin.', true, 'seed'),
  ('Magnesium Ascorbyl Phosphate', NULL, ARRAY['map']::text[], 'active', 0, 1, 6, ARRAY['sensitive']::text[], 'Stable vitamin C derivative with mild brightening/antioxidant benefit.', true, 'seed'),
  ('Ascorbyl Glucoside', NULL, ARRAY[]::text[], 'active', 0, 1, 6, ARRAY['sensitive']::text[], 'Stable vitamin C derivative, converts to active ascorbic acid in skin.', true, 'seed'),
  ('Tocopherol', NULL, ARRAY['vitamin e']::text[], 'active', 1, 0, 7, ARRAY['dry', 'mature', 'all']::text[], 'Antioxidant vitamin, often paired with vitamin C to boost stability.', true, 'seed'),
  ('Ferulic Acid', NULL, ARRAY[]::text[], 'active', 0, 1, 7, ARRAY['mature', 'all']::text[], 'Antioxidant that stabilizes and boosts the efficacy of vitamins C and E.', true, 'seed'),
  ('Alpha Arbutin', NULL, ARRAY[]::text[], 'active', 0, 1, 7, ARRAY['mature', 'normal']::text[], 'Tyrosinase-inhibiting brightening active, gentler than hydroquinone.', true, 'seed'),
  ('Azelaic Acid', NULL, ARRAY[]::text[], 'active', 0, 2, 8, ARRAY['acne-prone', 'sensitive', 'oily']::text[], 'Multi-purpose active for redness, tone, and mild acne; generally well tolerated.', true, 'seed'),
  ('Kojic Acid', NULL, ARRAY[]::text[], 'active', 0, 3, 6, ARRAY['mature']::text[], 'Brightening active; can be sensitizing at higher concentrations.', true, 'seed'),
  ('Tranexamic Acid', NULL, ARRAY[]::text[], 'active', 0, 1, 7, ARRAY['mature', 'sensitive']::text[], 'Brightening active that targets pigmentation with low irritation.', true, 'seed'),
  ('Resveratrol', NULL, ARRAY[]::text[], 'active', 0, 0, 6, ARRAY['mature', 'all']::text[], 'Polyphenol antioxidant with mild anti-aging benefits.', true, 'seed'),
  ('Green Tea Extract', NULL, ARRAY['camellia sinensis leaf extract']::text[], 'active', 0, 0, 6, ARRAY['oily', 'sensitive', 'all']::text[], 'Antioxidant plant extract with mild soothing and oil-control properties.', true, 'seed'),
  ('Centella Asiatica Extract', NULL, ARRAY['cica', 'gotu kola extract']::text[], 'active', 0, 0, 7, ARRAY['sensitive', 'acne-prone', 'all']::text[], 'Soothing, barrier-supportive extract popular for reactive/compromised skin.', true, 'seed'),
  ('Panax Ginseng Root Extract', NULL, ARRAY['ginseng extract']::text[], 'active', 0, 0, 5, ARRAY['mature']::text[], 'Antioxidant botanical extract with mild anti-aging associations.', true, 'seed'),
  ('Palmitoyl Pentapeptide-4', NULL, ARRAY['matrixyl']::text[], 'peptide', 0, 0, 6, ARRAY['mature']::text[], 'Signal peptide marketed to support collagen production.', true, 'seed'),
  ('Copper Tripeptide-1', NULL, ARRAY['copper peptides', 'ghk-cu']::text[], 'peptide', 0, 1, 6, ARRAY['mature']::text[], 'Peptide-mineral complex associated with wound healing and firmness support.', true, 'seed'),
  ('Acetyl Hexapeptide-8', NULL, ARRAY['argireline']::text[], 'peptide', 0, 0, 5, ARRAY['mature']::text[], 'Peptide marketed for a topical, temporary muscle-relaxing effect on fine lines.', true, 'seed'),
  ('Palmitoyl Tripeptide-1', NULL, ARRAY[]::text[], 'peptide', 0, 0, 5, ARRAY['mature']::text[], 'Signal peptide often combined with other peptides for firmness claims.', true, 'seed'),
  ('Phenoxyethanol', NULL, ARRAY[]::text[], 'preservative', 0, 1, 3, ARRAY['all']::text[], 'Broad-spectrum preservative, one of the most widely used and best tolerated.', true, 'seed'),
  ('Sodium Benzoate', NULL, ARRAY[]::text[], 'preservative', 0, 1, 3, ARRAY['all']::text[], 'Common preservative, effective at low pH.', true, 'seed'),
  ('Potassium Sorbate', NULL, ARRAY[]::text[], 'preservative', 0, 1, 3, ARRAY['all']::text[], 'Mild preservative typically paired with sodium benzoate.', true, 'seed'),
  ('Benzyl Alcohol', NULL, ARRAY[]::text[], 'preservative', 0, 2, 3, ARRAY[]::text[], 'Preservative/solvent; can be sensitizing for reactive skin at higher levels.', true, 'seed'),
  ('Ethylhexylglycerin', NULL, ARRAY[]::text[], 'preservative', 0, 0, 3, ARRAY['all']::text[], 'Preservative booster and mild skin conditioner.', true, 'seed'),
  ('Methylparaben', NULL, ARRAY['paraben']::text[], 'preservative', 0, 1, 2, ARRAY[]::text[], 'Widely studied preservative; generally well tolerated but a common consumer concern.', true, 'seed'),
  ('Propylparaben', NULL, ARRAY['paraben']::text[], 'preservative', 0, 1, 2, ARRAY[]::text[], 'Preservative from the paraben family, often used alongside methylparaben.', true, 'seed'),
  ('Chlorphenesin', NULL, ARRAY[]::text[], 'preservative', 0, 1, 2, ARRAY[]::text[], 'Preservative with mild antimicrobial activity.', true, 'seed'),
  ('Sodium Dehydroacetate', NULL, ARRAY[]::text[], 'preservative', 0, 1, 2, ARRAY[]::text[], 'Preservative used across a range of pH conditions.', true, 'seed'),
  ('Caprylyl Glycol', NULL, ARRAY[]::text[], 'preservative', 0, 0, 3, ARRAY['all']::text[], 'Preservative booster and mild humectant.', true, 'seed'),
  ('Disodium EDTA', NULL, ARRAY['edta']::text[], 'preservative', 0, 0, 2, ARRAY[]::text[], 'Chelating agent that improves preservative efficacy and product stability.', true, 'seed'),
  ('Benzoic Acid', NULL, ARRAY[]::text[], 'preservative', 0, 1, 2, ARRAY[]::text[], 'Preservative and pH adjuster, effective at acidic pH.', true, 'seed'),
  ('Fragrance', 'Parfum', ARRAY['parfum', 'perfume']::text[], 'fragrance', 0, 3, 1, ARRAY[]::text[], 'Undisclosed fragrance blend; a common trigger for sensitive skin.', true, 'seed'),
  ('Linalool', NULL, ARRAY[]::text[], 'fragrance', 0, 2, 1, ARRAY[]::text[], 'Common fragrance allergen, naturally occurring in many essential oils.', true, 'seed'),
  ('Limonene', NULL, ARRAY[]::text[], 'fragrance', 0, 2, 1, ARRAY[]::text[], 'Citrus-derived fragrance component and known contact allergen.', true, 'seed'),
  ('Citronellol', NULL, ARRAY[]::text[], 'fragrance', 0, 2, 1, ARRAY[]::text[], 'Fragrance component associated with contact sensitization in some users.', true, 'seed'),
  ('Geraniol', NULL, ARRAY[]::text[], 'fragrance', 0, 2, 1, ARRAY[]::text[], 'Common fragrance allergen found in rose- and geranium-scented products.', true, 'seed'),
  ('Eugenol', NULL, ARRAY[]::text[], 'fragrance', 0, 3, 1, ARRAY[]::text[], 'Clove-derived fragrance component, a recognized sensitizer.', true, 'seed'),
  ('Lavender Oil', NULL, ARRAY['lavandula angustifolia oil']::text[], 'fragrance', 0, 2, 2, ARRAY[]::text[], 'Essential oil with a pleasant scent but real sensitization potential.', true, 'seed'),
  ('Tea Tree Oil', NULL, ARRAY['melaleuca alternifolia oil']::text[], 'fragrance', 0, 3, 4, ARRAY['oily']::text[], 'Antimicrobial essential oil with acne-related benefits, but irritating undiluted.', true, 'seed'),
  ('Peppermint Oil', NULL, ARRAY['mentha piperita oil']::text[], 'fragrance', 0, 3, 1, ARRAY[]::text[], 'Cooling essential oil that frequently irritates sensitive or compromised skin.', true, 'seed'),
  ('Citrus Extract', NULL, ARRAY['citrus limon peel extract']::text[], 'fragrance', 0, 2, 2, ARRAY[]::text[], 'Botanical extract used for scent; can be irritating, especially with sun exposure.', true, 'seed'),
  ('Ylang Ylang Oil', NULL, ARRAY['cananga odorata flower oil']::text[], 'fragrance', 0, 2, 1, ARRAY[]::text[], 'Floral essential oil, common fragrance allergen source.', true, 'seed'),
  ('Rose Oil', NULL, ARRAY['rosa damascena flower oil']::text[], 'fragrance', 0, 2, 2, ARRAY[]::text[], 'Floral essential oil valued for scent; can sensitize reactive skin.', true, 'seed'),
  ('Alcohol Denat.', NULL, ARRAY['denatured alcohol', 'sd alcohol']::text[], 'alcohol', 0, 3, 2, ARRAY['oily']::text[], 'Fast-drying solvent alcohol; can be drying/irritating for dry or sensitive skin.', true, 'seed'),
  ('Cetyl Alcohol', NULL, ARRAY[]::text[], 'alcohol', 1, 0, 5, ARRAY['dry', 'all']::text[], 'Fatty alcohol emollient/thickener; not drying despite the name.', true, 'seed'),
  ('Stearyl Alcohol', NULL, ARRAY[]::text[], 'alcohol', 1, 0, 5, ARRAY['dry', 'all']::text[], 'Fatty alcohol used as an emollient and thickener; non-drying.', true, 'seed'),
  ('Isopropyl Alcohol', NULL, ARRAY[]::text[], 'alcohol', 0, 4, 1, ARRAY[]::text[], 'Strong drying solvent alcohol; can compromise the skin barrier with frequent use.', true, 'seed'),
  ('Behenyl Alcohol', NULL, ARRAY[]::text[], 'alcohol', 1, 0, 4, ARRAY['dry']::text[], 'Fatty alcohol emollient/thickener, non-drying.', true, 'seed'),
  ('Cyclopentasiloxane', NULL, ARRAY[]::text[], 'silicone', 0, 0, 5, ARRAY['all']::text[], 'Volatile silicone that gives a silky finish and evaporates cleanly.', true, 'seed'),
  ('Dimethiconol', NULL, ARRAY[]::text[], 'silicone', 0, 0, 5, ARRAY['dry', 'all']::text[], 'Silicone conditioning agent that adds slip and shine.', true, 'seed'),
  ('Cyclohexasiloxane', NULL, ARRAY[]::text[], 'silicone', 0, 0, 5, ARRAY['all']::text[], 'Volatile silicone used for a lightweight, smooth finish.', true, 'seed'),
  ('Phenyl Trimethicone', NULL, ARRAY[]::text[], 'silicone', 0, 0, 5, ARRAY['all']::text[], 'Silicone that adds shine and a smooth after-feel.', true, 'seed'),
  ('Dimethicone Crosspolymer', NULL, ARRAY[]::text[], 'silicone', 0, 0, 5, ARRAY['all']::text[], 'Gel-forming silicone that softens the appearance of pores and lines.', true, 'seed'),
  ('Zinc Oxide', NULL, ARRAY[]::text[], 'sunscreen-filter', 0, 0, 9, ARRAY['sensitive', 'acne-prone', 'all']::text[], 'Broad-spectrum mineral UV filter, well tolerated by sensitive/reactive skin.', true, 'seed'),
  ('Titanium Dioxide', NULL, ARRAY[]::text[], 'sunscreen-filter', 1, 0, 8, ARRAY['sensitive', 'all']::text[], 'Mineral UV filter, mainly UVB with some UVA protection.', true, 'seed'),
  ('Avobenzone', NULL, ARRAY[]::text[], 'sunscreen-filter', 0, 1, 7, ARRAY['normal']::text[], 'Chemical UVA filter, often paired with stabilizers due to photoinstability.', true, 'seed'),
  ('Octinoxate', NULL, ARRAY['ethylhexyl methoxycinnamate']::text[], 'sunscreen-filter', 0, 1, 6, ARRAY['normal']::text[], 'Chemical UVB filter, widely used but with some environmental concerns.', true, 'seed'),
  ('Octocrylene', NULL, ARRAY[]::text[], 'sunscreen-filter', 1, 1, 6, ARRAY['normal']::text[], 'Chemical UVB filter that also stabilizes avobenzone.', true, 'seed'),
  ('Homosalate', NULL, ARRAY[]::text[], 'sunscreen-filter', 0, 1, 5, ARRAY['normal']::text[], 'Chemical UVB filter commonly used in sunscreen blends.', true, 'seed'),
  ('Bemotrizinol', NULL, ARRAY['tinosorb s']::text[], 'sunscreen-filter', 0, 0, 8, ARRAY['sensitive', 'normal']::text[], 'Broad-spectrum, photostable chemical UV filter with a strong tolerability profile.', true, 'seed'),
  ('Bisoctrizole', NULL, ARRAY['tinosorb m']::text[], 'sunscreen-filter', 0, 0, 8, ARRAY['sensitive', 'normal']::text[], 'Broad-spectrum organic/mineral hybrid UV filter, well tolerated.', true, 'seed'),
  ('Ensulizole', NULL, ARRAY[]::text[], 'sunscreen-filter', 0, 1, 5, ARRAY['normal']::text[], 'Water-soluble chemical UVB filter.', true, 'seed'),
  ('Diethylamino Hydroxybenzoyl Hexyl Benzoate', NULL, ARRAY['uvinul a plus']::text[], 'sunscreen-filter', 0, 0, 7, ARRAY['sensitive', 'normal']::text[], 'Photostable UVA filter used to round out broad-spectrum protection.', true, 'seed'),
  ('Sodium Laureth Sulfate', NULL, ARRAY['sles']::text[], 'surfactant', 0, 3, 4, ARRAY['oily']::text[], 'Strong foaming cleanser; can be drying/irritating with frequent use.', true, 'seed'),
  ('Sodium Lauryl Sulfate', NULL, ARRAY['sls']::text[], 'surfactant', 0, 4, 3, ARRAY[]::text[], 'Strong foaming cleanser with a higher irritation potential than SLES.', true, 'seed'),
  ('Cocamidopropyl Betaine', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 6, ARRAY['sensitive', 'all']::text[], 'Mild, coconut-derived co-surfactant commonly used to soften harsher cleansers.', true, 'seed'),
  ('Decyl Glucoside', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 7, ARRAY['sensitive', 'dry', 'all']::text[], 'Gentle sugar-derived surfactant, well tolerated by sensitive skin.', true, 'seed'),
  ('Sodium Cocoyl Isethionate', NULL, ARRAY['sci']::text[], 'surfactant', 0, 1, 7, ARRAY['sensitive', 'dry', 'all']::text[], 'Mild coconut-derived surfactant popular in "gentle" cleansing bars/washes.', true, 'seed'),
  ('Lauryl Glucoside', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 6, ARRAY['sensitive', 'all']::text[], 'Mild sugar-derived surfactant used to boost foam without harsh sulfates.', true, 'seed'),
  ('Coco-Glucoside', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 6, ARRAY['sensitive', 'all']::text[], 'Gentle non-ionic surfactant derived from coconut and fruit sugars.', true, 'seed'),
  ('Disodium Cocoamphodiacetate', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 6, ARRAY['sensitive']::text[], 'Mild amphoteric surfactant used to reduce irritation in cleansers.', true, 'seed'),
  ('Sodium Cocoyl Glutamate', NULL, ARRAY[]::text[], 'surfactant', 0, 1, 7, ARRAY['sensitive', 'dry', 'all']::text[], 'Amino-acid-derived surfactant, gentle and mildly moisturizing.', true, 'seed'),
  ('Potassium Cocoate', NULL, ARRAY[]::text[], 'surfactant', 0, 2, 5, ARRAY['oily']::text[], 'Saponified-oil-based surfactant used in traditional cleansing bars.', true, 'seed'),
  ('Xanthan Gum', NULL, ARRAY[]::text[], 'thickener', 0, 0, 2, ARRAY['all']::text[], 'Natural polysaccharide thickener with no known skin activity.', true, 'seed'),
  ('Carbomer', NULL, ARRAY[]::text[], 'thickener', 0, 0, 2, ARRAY['all']::text[], 'Synthetic gelling agent used to build gel and lotion textures.', true, 'seed'),
  ('Sodium Polyacrylate', NULL, ARRAY[]::text[], 'thickener', 0, 0, 2, ARRAY['all']::text[], 'Thickening polymer used to adjust product viscosity.', true, 'seed'),
  ('Hydroxyethylcellulose', NULL, ARRAY[]::text[], 'thickener', 0, 0, 2, ARRAY['all']::text[], 'Cellulose-derived thickener with no known skin activity.', true, 'seed'),
  ('Acrylates/C10-30 Alkyl Acrylate Crosspolymer', NULL, ARRAY[]::text[], 'thickener', 0, 0, 2, ARRAY['all']::text[], 'Thickening/stabilizing polymer used in gels and emulsions.', true, 'seed'),
  ('PVP', NULL, ARRAY['polyvinylpyrrolidone']::text[], 'film-former', 0, 0, 2, ARRAY['all']::text[], 'Film-forming polymer used to improve product hold and texture.', true, 'seed'),
  ('Mica', NULL, ARRAY[]::text[], 'colorant', 0, 0, 1, ARRAY['all']::text[], 'Mineral pigment used for shimmer/color; inert on skin.', true, 'seed'),
  ('Titanium Dioxide (colorant use)', 'CI 77891', ARRAY['ci 77891']::text[], 'colorant', 1, 0, 1, ARRAY['all']::text[], 'White pigment used for opacity/color in makeup-adjacent formulas.', true, 'seed'),
  ('Iron Oxides', 'CI 77491, CI 77492, CI 77499', ARRAY['ci 77491', 'ci 77492', 'ci 77499']::text[], 'colorant', 0, 0, 1, ARRAY['all']::text[], 'Mineral pigments used for tinting; also help block visible/blue light.', true, 'seed'),
  ('Red 40', 'CI 16035', ARRAY['ci 16035']::text[], 'colorant', 0, 1, 0, ARRAY[]::text[], 'Synthetic dye used for color; occasional sensitizer.', true, 'seed'),
  ('Blue 1', 'CI 42090', ARRAY['ci 42090']::text[], 'colorant', 0, 1, 0, ARRAY[]::text[], 'Synthetic dye used for color in cosmetic formulas.', true, 'seed'),
  ('Allantoin', NULL, ARRAY[]::text[], 'active', 0, 0, 6, ARRAY['sensitive', 'dry', 'all']::text[], 'Soothing, skin-conditioning agent, often used to calm reactive formulas.', true, 'seed'),
  ('Bisabolol', NULL, ARRAY[]::text[], 'active', 0, 0, 6, ARRAY['sensitive', 'all']::text[], 'Chamomile-derived soothing agent used to calm irritation.', true, 'seed'),
  ('Chamomile Extract', NULL, ARRAY['matricaria chamomilla extract', 'anthemis nobilis extract']::text[], 'active', 0, 1, 5, ARRAY['sensitive']::text[], 'Soothing botanical extract; rare sensitizer for ragweed-allergic individuals.', true, 'seed'),
  ('Licorice Root Extract', NULL, ARRAY['glycyrrhiza glabra root extract']::text[], 'active', 0, 0, 6, ARRAY['sensitive', 'mature']::text[], 'Soothing, mildly brightening botanical extract.', true, 'seed'),
  ('Witch Hazel', NULL, ARRAY['hamamelis virginiana extract']::text[], 'active', 0, 2, 4, ARRAY['oily']::text[], 'Astringent botanical extract; formulations with alcohol can be drying.', true, 'seed'),
  ('Zinc PCA', NULL, ARRAY[]::text[], 'active', 0, 0, 6, ARRAY['oily', 'acne-prone']::text[], 'Zinc salt used for mild oil-control and soothing benefits.', true, 'seed'),
  ('Caffeine', NULL, ARRAY[]::text[], 'active', 0, 0, 5, ARRAY['oily', 'normal']::text[], 'Antioxidant with mild de-puffing and vasoconstrictive properties.', true, 'seed'),
  ('Niacin', NULL, ARRAY['nicotinic acid']::text[], 'active', 0, 2, 4, ARRAY[]::text[], 'Vitamin B3 precursor; can cause temporary flushing, unlike niacinamide.', true, 'seed'),
  ('Adenosine', NULL, ARRAY[]::text[], 'active', 0, 0, 6, ARRAY['mature']::text[], 'Anti-wrinkle active recognized in several regulatory markets.', true, 'seed'),
  ('Beta-Glucan', NULL, ARRAY[]::text[], 'humectant', 0, 0, 6, ARRAY['sensitive', 'dry', 'all']::text[], 'Soothing polysaccharide that supports hydration and barrier repair.', true, 'seed'),
  ('Ceramide NP', NULL, ARRAY['ceramide 3']::text[], 'emollient', 0, 0, 8, ARRAY['dry', 'sensitive', 'mature', 'all']::text[], 'Barrier lipid that replenishes the skin’s natural ceramide content.', true, 'seed'),
  ('Cholesterol', NULL, ARRAY[]::text[], 'emollient', 0, 0, 6, ARRAY['dry', 'mature']::text[], 'Barrier lipid, often combined with ceramides and fatty acids.', true, 'seed'),
  ('Linoleic Acid', NULL, ARRAY[]::text[], 'emollient', 1, 0, 6, ARRAY['acne-prone', 'oily']::text[], 'Essential fatty acid associated with a lower comedogenic profile than oleic acid.', true, 'seed'),
  ('Squalene', NULL, ARRAY[]::text[], 'emollient', 2, 0, 5, ARRAY['dry']::text[], 'Unsaturated precursor to squalane; less stable and slightly more comedogenic.', true, 'seed'),
  ('Niacinamide/Zinc PCA Complex', NULL, ARRAY[]::text[], 'active', 0, 1, 8, ARRAY['oily', 'acne-prone']::text[], 'Combination active formulated for oil regulation and pore appearance.', true, 'seed'),
  ('Panthenyl Triacetate', NULL, ARRAY[]::text[], 'humectant', 0, 0, 5, ARRAY['dry', 'all']::text[], 'Oil-soluble form of panthenol, used in emollient-rich formulas.', true, 'seed'),
  ('Sea Buckthorn Oil', NULL, ARRAY['hippophae rhamnoides oil']::text[], 'emollient', 2, 0, 6, ARRAY['dry', 'mature']::text[], 'Carotenoid-rich oil valued for antioxidant and barrier-support properties.', true, 'seed'),
  ('Evening Primrose Oil', NULL, ARRAY['oenothera biennis oil']::text[], 'emollient', 2, 0, 6, ARRAY['dry', 'sensitive']::text[], 'GLA-rich oil associated with barrier support and mild anti-inflammatory benefit.', true, 'seed'),
  ('Meadowfoam Seed Oil', NULL, ARRAY['limnanthes alba seed oil']::text[], 'emollient', 1, 0, 6, ARRAY['dry', 'combination', 'all']::text[], 'Highly stable, lightweight emollient oil.', true, 'seed'),
  ('Sodium Hyaluronate Crosspolymer', NULL, ARRAY[]::text[], 'humectant', 0, 0, 8, ARRAY['dry', 'mature', 'all']::text[], 'Cross-linked hyaluronic acid that forms a hydrating film on the skin surface.', true, 'seed')
on conflict (canonical_name) do update set
  inci_name = excluded.inci_name,
  aliases = excluded.aliases,
  category = excluded.category,
  comedogenic_rating = excluded.comedogenic_rating,
  irritancy_rating = excluded.irritancy_rating,
  benefit_score = excluded.benefit_score,
  skin_type_fit = excluded.skin_type_fit,
  description = excluded.description,
  is_rated = excluded.is_rated,
  source = excluded.source,
  updated_at = now();
